#DB
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: 1234
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: vote

# 연결정보 - 로컬
BASE_URL: http://localhost:8080
FRONT_URL: http://localhost:3000

REDIS_HOST: localhost
REDIS_PORT: 6379
